- hosts: all
  become: yes
  gather_facts: no

  vars:
    ubuntu_package_list:
      - ufw
      - emacs
      - monit
      - fail2ban
      - python-pip
      - python-virtualenv
      - unattended-upgrades

    python_module_list:
      - requests

  pre_tasks:
    - name: Install Python 2
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Gathering facts
      setup:

    - name: Update package cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade system
      apt: upgrade=dist

    - name: Install required packages
      apt: name={{item}} state=installed
      with_items: "{{ubuntu_package_list}}"

    - name: Install required python modules
      pip: name={{item}}
      with_items: "{{python_module_list}}"

    - name: Adjust automatic update intervals
      copy: src=apt_periodic_updates.conf dest=/etc/apt/apt.conf.d/10periodic

    - name: Automate security updates only
      copy: src=apt_unattended_updates.conf dest=/etc/apt/apt.conf.d/50unattended-upgrades

    - name: Setup ufw
      ufw: state=enabled policy=deny

    - name: Allow SSH traffic
      ufw: rule=allow port=22 proto=tcp

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: Restart ssh

    - name: Copy monit alert script
      copy: src=monit_ssh_alert.py dest=/etc/monit/ssh-alert.py mode="u=rx"

    - name: Copy monit ssh login configuration 
      copy: src=monit_ssh_logins.conf dest=/etc/monit/conf.d/ssh-logins

    - name: Update monit update interval
      lineinfile: dest=/etc/monit/monitrc
                  regexp="^set daemon"
                  line="set daemon 5"
                  state=present
      notify: Restart monit

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

    - name: Restart monit
      service: name=monit state=restarted