- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Install Python 2
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Gathering facts
      setup:
    
    - include: apt.yml
    
    - include: pip.yml
    
    - include: ssh.yml
    
    - include: monit.yml
      when: not (slack_webhook == "")
